### ISSUE TITLE
ROS kinetic compatibility

### ISSUE THREAD

**Issue by diegocdl** [eaa3/perception_neuron_ros_win_server#1]
Hi, I'm facing troubles to get this code work on ROS kinetic and Ubuntu 16.04...
Have you ever tested this on ROS kinetic?

**Comment by eaa3** [comment]
Hey, I haven't had the chance to test on ROS kinetic yet. But if you can test it, that would be much appreciated. I can confirm it works fine on ROS Indigo and Ubuntu 14.04, as we've been running experiments on this setup.

**Comment by muealexi** [comment]
I tried getting it to work on kinetic as well and it does not seem to work either. 

But I am not sure if the problem lies on the windows side or on the linux side. The executable does not seem to send the data correctly to ROS

**Comment by diegocdl** [comment]
@muealexi I remove the `Sleep(1000)`  from `src/PerceptionNeuronROSserial.cpp` line 209 and I also change the condition of the line 218 from
`if (_valuesBuffer[114]) {`
to 
`if (_valuesBuffer != NULL && _valuesBuffer[114]) {`

 and it worked, can you try if this works for you ?

I'm using 
* Ubuntu 16.04
* ROS Kinetic
* Windows 10
* Axis Neuron Pro 3.8.42.6503
* Visual Studio 2017

**Comment by muealexi** [comment]
@diegocdl  Perfect! Thanks a lot! now it works nicely!

**Comment by eaa3** [comment]
@diegocdl Good stuff! Would you mind committing your changes in a separate branch for ROS Kinetic and making a pull request?
